export default [
  'Abbott',
  'Abdi Ibrahim',
  'Aburaihan',
  'Aksufarma Ilac San',
  'Alpha Pharma',
  'Apex Pharma',
  'Aspen',
  'Astrazeneca',
  'Banford',
  'Bayer',
  'Bayer Zydus Pharma',
  'Beligas',
  'Bharat Serums And Vaccines',
  'Bilim',
  'Bioteq Labs',
  'Cenzo Pharma',
  'Cipla',
  'Concern Pharma',
  'Deus Medical',
  'Deva',
  'Drooc Pharma',
  'Elixir Meds',
  'Elysium Meds',
  'Euro-Pharmacies',
  'Europe Gt',
  'Ferring',
  'Generics',
  'Genetic Pharma',
  'Godtropin',
  'Gsk',
  'Hab Pharma',
  'Healing Pharma',
  'Hilma Biocare',
  'Himalaya',
  'Ibsa',
  'Ice Pharma',
  'Intex Pharma',
  'Iran Hormone',
  'Ironlion Lab',
  'Knoll Healthcare',
  'Kocak Farma',
  'Lilly',
  'Magnum Laboratories',
  'Merck',
  'Msd',
  'Nexus Labs',
  'Nobel',
  'Novartis',
  'Novo Nordisk',
  'Odin Pharma',
  'Omstal Pharma',
  'Para Pharma',
  'Pfizer',
  'Pharmacom Labs',
  'Pharmaqo',
  'Pivotal Labs',
  'Roche',
  'Roid Plus',
  'Sandoz',
  'Sanofi',
  'Satan Pharma',
  'Servier',
  'Sopharma',
  'Sun Pharma',
  'Sunrise Remedies',
  'Teva Pharmaceutical',
  'U.K. Pharmaceutical',
  'Ultima Pharma',
  'Zerox Pharma',
  'Zydus Cadila Healthcare',
];
